import type { Metadata } from "next";
import { getAfterpartyByToken } from "@/lib/page-data";
import { Countdown } from "@/components/afterparty/Countdown";
import { AfterpartyBoard } from "@/components/afterparty/AfterpartyBoard";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const data = await getAfterpartyByToken(token);
  if (data.state !== "live" || !data.you) {
    return { title: "afterparty.digital" };
  }
  const title = `${data.you.name}'s afterparty · ${data.event!.name}`;
  const description = `${data.event!.attendeeCount} people were in the room. Here's who ${data.you.name.split(" ")[0]} should reach out to.`;
  return {
    title,
    description,
    openGraph: { title, description, type: "profile" },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function AfterpartyPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const data = await getAfterpartyByToken(token);

  if (data.state === "not_found") {
    return (
      <Shell>
        <div className="text-center">
          <h1 className="text-3xl font-bold">This afterparty doesn&apos;t exist</h1>
          <p className="mt-3 text-white/60">The link may be mistyped, or the page has dissolved.</p>
        </div>
      </Shell>
    );
  }

  if (data.state === "dissolved") {
    return (
      <Shell>
        <div className="text-center">
          <h1 className="text-3xl font-bold">The afterparty has ended</h1>
          <p className="mt-3 max-w-md text-white/60">
            {data.event?.name ? `“${data.event.name}” ` : "This event "}
            has dissolved. The connections were yours to keep — we don&apos;t hold onto the data.
          </p>
        </div>
      </Shell>
    );
  }

  const { you, event, clusters = [], recommendations = [], marked = [], others = [] } = data;

  return (
    <Shell>
      <div className="mx-auto max-w-3xl">
        {/* Hero */}
        <header className="text-center">
          <p className="text-sm font-medium uppercase tracking-[0.2em] text-fuchsia-300/80">
            {event!.name}
          </p>
          <h1 className="mt-3 text-4xl font-extrabold leading-tight sm:text-5xl">
            Hey {you!.name.split(" ")[0]} —<br />
            <span className="bg-gradient-to-r from-fuchsia-300 via-pink-300 to-amber-200 bg-clip-text text-transparent">
              here was your room
            </span>
          </h1>
          <p className="mx-auto mt-4 max-w-xl text-white/70">
            You shared this event with{" "}
            <span className="font-semibold text-white">{event!.attendeeCount} people</span>. The night&apos;s
            over, but the best connections haven&apos;t happened yet. Here&apos;s where to start.
          </p>
          {clusters.length > 0 && (
            <div className="mt-5 flex flex-wrap justify-center gap-2">
              {clusters.map((c) => (
                <span
                  key={c}
                  className="rounded-full border border-white/15 bg-white/5 px-3 py-1 text-xs font-medium text-white/80"
                >
                  {c}
                </span>
              ))}
            </div>
          )}
        </header>

        {/* Countdown */}
        {event!.dissolvesAt && (
          <div className="mx-auto mt-10 max-w-md">
            <Countdown dissolvesAt={event!.dissolvesAt} />
          </div>
        )}

        {/* Interactive board */}
        <div className="mt-12">
          <AfterpartyBoard
            token={token}
            you={{ id: you!.id, name: you!.name }}
            initialRecommendations={recommendations}
            initialMarked={marked}
            others={others}
          />
        </div>

        {/* Privacy footer */}
        <footer className="mt-16 border-t border-white/10 pt-6 text-center text-xs text-white/40">
          Generated by afterparty.digital from the event&apos;s attendee list. We never claim who you
          actually met — only who&apos;s worth meeting. This page is yours, and only yours, until it dissolves.
        </footer>
      </div>
    </Shell>
  );
}

function Shell({ children }: { children: React.ReactNode }) {
  return (
    <main className="relative min-h-screen overflow-hidden bg-[#0b0613] text-white">
      {/* vibrant celebratory gradient wash */}
      <div className="pointer-events-none absolute inset-0 -z-10">
        <div className="absolute -top-40 left-1/2 h-[42rem] w-[42rem] -translate-x-1/2 rounded-full bg-fuchsia-600/30 blur-[120px]" />
        <div className="absolute top-1/3 -left-32 h-[28rem] w-[28rem] rounded-full bg-indigo-600/30 blur-[120px]" />
        <div className="absolute bottom-0 right-0 h-[26rem] w-[26rem] rounded-full bg-amber-500/20 blur-[120px]" />
      </div>
      <div className="flex min-h-screen flex-col items-center justify-center px-6 py-16">{children}</div>
    </main>
  );
}
